# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bitpie.com
title: bitpie - Best Bitcoin Wallet!
email: bitpiedotcom@gmail.com
author: getcai
description:  bitpie - Best Bitcoin Wallet!
copyright: '&copy; 2016 bitpie.com'
credits: 'The bitpie wallet is based on'
creditss: "technology."
logo: img/logo.png
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Email
    url: mailto:bitpiedotcom@gmail.com
  - title: QQ group:493077876
    url: http://shang.qq.com/wpa/qunwpa?idkey=75a7c3c46c97658b589c7b1b35ddbb2ea82bb76954154ecd9c59e360961c22ac
 
# ----------------------- #
#   download index.html   #
# ----------------------- #
downtitle: 比特派
downsoftname: 比特派
iosdownsoftversion: 1.1.5
iosdownsoftdate: 2016-12-26
anddownsoftversion: 1.1.5
anddownsoftdate: 2017-01-04

downqr: '/img/ios_qr.png'
downlogo: '/img/bitpie_ios_144.png'
lesson: bitpie iOS安装教程
downmobilefirsttitle: 1.第一次打开bitpie的时候会弹出如下框
downmobilefirst: '/img/MobileIOSStep1.png'
downmobilesecondtitle: 2.在手机的设置-通用-描述文件与设备管理，信任下面的文件
downmobilesecond: '/img/MobileIOSStep2.png'
downmobilethreetitle: 3.信任下面的证书就可以启动bitpie了
downmobilethree: '/img/MobileIOSStep3.png'
downhttps: 'https://bitpiedotcom.github.io'
appstore: 'https://itunes.apple.com/us/app/bitpie-bitcoin-wallet/id1168568820'

# ----------------------- #
# android download.index   #
# ----------------------- #
androidsoftname: 'Bitpie Android'
androidqr: '/img/android_qr.png'
androidlogo: '/img/logo.png'
androidsha: 'https://github.com/bitpiedotcom/bitpiedotcom.github.com/raw/master/android/SHA256SUMS'
googleplay: 'https://play.google.com/store/apps/details?id=com.bitpie'


# ----------------------- #
#   download link   #
# ----------------------- #
apkdown: 'https://github.com/bitpiedotcom/bitpiedotcom.github.com/raw/master/android/bitpie.apk'
apkdownq: 'https://dn-bither.qbox.me/bitpie.apk'