# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bitpie.com
title: bitpie - Best Bitcoin Wallet!
email: bitpiedotcom@gmail.com
author: getcai
description:  bitpie - Best Bitcoin Wallet!
copyright: '&copy; 2017 bitpie.com'
credits: 'The bitpie wallet is based on'
creditss: "technology."
logo: img/logo.png
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Email
    url: mailto:bitpiedotcom@gmail.com
  - title: QQ group 1:493077876
    url: //shang.qq.com/wpa/qunwpa?idkey=a81694d6b01e387306c7504f3448dd25eccbf9f74b652c3bf057e33afc59e1b4
  - title: QQ group 2:431191173
    url: //shang.qq.com/wpa/qunwpa?idkey=0d36de627d3963995945f1eebcff75c01f45ab5b7645c1c35f94379ab574eaa8
  - title: QQ group 3:616697070
    url: //shang.qq.com/wpa/qunwpa?idkey=4051ff572575ab006936d29e41ae420cbae0f25f3d41c404a5f120fb430ffa53

 
# ----------------------- #
#   download index.html   #
# ----------------------- #
downtitle: 比特派
downsoftname: 比特派
iosdownsoftversion: 2.2.1
iosdownsoftdate: 2017-09-12
anddownsoftversion: 2.2.1
anddownsoftdate: 2017-09-12

downqr: '/img/ios_qr.png'
downlogo: '/img/bitpie_ios_144.png'
lesson: bitpie iOS安装教程
downmobilefirsttitle: 1.第一次打开bitpie的时候会弹出如下框
downmobilefirst: '/img/MobileIOSStep1.png'
downmobilesecondtitle: 2.在手机的设置-通用-描述文件与设备管理，信任下面的文件
downmobilesecond: '/img/MobileIOSStep2.png'
downmobilethreetitle: 3.信任下面的证书就可以启动bitpie了
downmobilethree: '/img/MobileIOSStep3.png'
downhttps: 'https://bitpiedotcom.github.io'
appstore: 'https://itunes.apple.com/us/app/bitpie-bitcoin-wallet/id1168568820'
winxin: '/img/weixin.png'
step1: '/img/step1.png'
step2: '/img/step2.png'
step3: '/img/step3.png'

# ----------------------- #
# android download.index   #
# ----------------------- #
androidsoftname: 'Bitpie Android'
androidqr: '/img/android_qr.png'
androidlogo: '/img/logo.png'
androidsha: 'https://github.com/bitpiedotcom/bitpiedotcom.github.com/raw/master/android/SHA256SUMS'
googleplay: 'https://play.google.com/store/apps/details?id=com.bitpie'


# ----------------------- #
#   download link   #
# ----------------------- #
apkdown: 'https://github.com/bitpiedotcom/bitpiedotcom.github.com/raw/master/android/bitpie.apk'
apkdownq: 'https://dn-bither.qbox.me/bitpie.apk'

# Gems
gems:
  - jekyll-paginate


# Permalinks
permalink:      /:year-:month-:day/:title


paginate:       5

# Build settings
markdown:       kramdown